version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - chatnet

  api:
    build: ./api
    ports:
      - "8100:8100"
    depends_on:
      - redis
    networks:
      - chatnet

  socket_server:
    build: ./socket_server
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - chatnet

networks:
  chatnet:

